language: swift
osx_image: xcode10.1

git:
  submodules: false

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - DI_LINTER_PROJECT_FOLDER=$TRAVIS_BUILD_DIR
script:
  - swift package resolve
  - swift test
notifications:
  email:
    on_success: never