language: swift
osx_image: xcode11

git:
  submodules: false
github_token: $GITHUB_TOKEN
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - DI_LINTER_DEFAULT_TARGET='x86_64-apple-macosx10.10'
before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.33.0/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - curl -L -O https://github.com/realm/SwiftLint/releases/download/0.28.2/SwiftLint.pkg
  - sudo installer -pkg SwiftLint.pkg -target /
  - bundle install
  - brew install make
  - swift package resolve
script:
  - swiftlint
  - make test
notifications:
  email:
    on_success: never