language: swift
osx_image: xcode10.1

git:
  submodules: false

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - DI_LINTER_PROJECT_FOLDER=$TRAVIS_BUILD_DIR
before_install:
  - curl -L -O https://github.com/realm/SwiftLint/releases/download/0.28.2/SwiftLint.pkg
  - sudo installer -pkg SwiftLint.pkg -target /
script:
  - swift package resolve
  - swiftlint
  - swift test
notifications:
  email:
    on_success: never